<?php
use Nette\Application\Routers\Route, 
    Nette\Application\Routers\RouteList,
    Dan\RestRoute;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../vendor')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon', $configurator::AUTO);
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();


$container->router[] = $adminRouter = new RouteList('Admin');
$adminRouter[] = new Route('administration/<action>', 'Admin:default');

$container->router[] = $apiRouter = new RouteList('Api');
$apiRouter[] = new RestRoute(
	'api/<presenter>[/<id>]', 
	array(
		'presenter' => 'Days',
		'action' => 'default',
		'id' => null,
	), 
	RestRoute::RESTFUL
);

$container->router[] = $frontRouter = new RouteList('Front');
$frontRouter[] = new Route(
	'<presenter home|signin|signup|account|test>/<action>[/<id>]', 
	array(
		'presenter' => 'Home',
		'action' => 'default',
		'id' => null
	)
);
//$frontRouter[] = new Route('<presenter account>/<action>', 'Account:credentials');

return $container;
